image: ghcr.io/firemetrics/fmx-panel:v1.2.2
serviceAccountName: ""
imagePullSecret: ""
initContainers: []
securityContext: {}
env: []
volumes: []
volumeMounts: []

# -- The features enabled in the Panel.
featureFlags:
  - resource_explorer
  - nocode_builder
  - sql_editor

publicUrl: "https://example.com/panel"
publicPath: "/panel"

database:
  hostname: postgres
  dbname: firemetrics
  port: 5432
  userSecret:
    name: panel-db-user
    usernameKey: username
    passwordKey: password

bootstrapDatabase:
  enabled: false
  image: ghcr.io/zalando/spilo-17:4.0-p2
  databaseUserSecret:
    name: panel-bootstrap-db-user
    usernameKey: username
    passwordKey: password

bootstrapKeycloak:
  enabled: false
  image: curlimages/curl:8.15.0
  url: "https://example.com/auth"
  realm: "firemetrics"
  adminUserSecret:
    name: keycloak-admin
    usernameKey: username
    passwordKey: password

oidc:
  enabled: false
  discoveryUrl: ""
  # -- Defaults to the public URL.
  audience: ""
  clientSecret:
    name: panel-oidc-client
    idKey: id
    secretKey: secret

fhirBaseUrl: "https://example.com/fhir"

grafanaUrl: ""

openaiApiKeySecret:
  enabled: false
  name: openai-api-key
  key: api-key

caCertsConfigMap:
  enabled: false
  name: "ca-certs"
  fileName: "ca-certificates.crt"
