{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) .Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "appName" . }}
spec:
  commonName: {{ include "fqdn" . | quote }}
  secretName: {{ include "tlsCertSecretName" . }}
  dnsNames:
    - {{ include "fqdn" . | quote }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.tls.certManager.issuer | quote }}
{{- end }}
