{{- if .Values.components.fuego.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "fuegoAppName" . }}
  namespace: {{ .Values.argoCdNamespace | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.chartRepoUrl | quote }}
    {{ include "chartSelection" (dict "context" . "chart" "fuego") }}
    targetRevision: {{ include "chartRevision" . | quote }}
    helm:
      releaseName: {{ include "fuegoAppName" . }}
      values: |
      {{- if .Values.components.fuego.valuesOverride }}
        {{- .Values.components.fuego.valuesOverride | toYaml | nindent 8 }}
      {{- else }}
        image: {{ .Values.components.fuego.image | quote }}
        imagePullSecret: {{ .Values.imagePullSecret | quote }}

        {{- with .Values.components.fuego.securityContext }}
        securityContext: {{- . | toYaml | nindent 10 }}
        {{- end }}

        {{- with .Values.components.fuego.env }}
        env: {{ . | toYaml | nindent 10 }}
        {{- end }}

        logging:
          format: {{ .Values.components.fuego.logging.format | quote }}

        {{- with .Values.components.fuego.volumes }}
        volumes: {{ . | toYaml | nindent 10 }}
        {{- end }}

        {{- with .Values.components.fuego.volumeMounts }}
        volumeMounts: {{ . | toYaml | nindent 10 }}
        {{- end }}

        {{- with .Values.components.fuego.livenessProbe }}
        livenessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}

        {{- with .Values.components.fuego.readinessProbe }}
        readinessProbe: {{ . | toYaml | nindent 10 }}
        {{- end }}

        {{- if and .Values.oidc.enabled .Values.components.keycloak.enabled }}
        bootstrapKeycloak:
          enabled: true
          url: {{ include "keycloakPublicUrl" . | quote }}
          realm: {{ .Values.oidc.keycloakRealm | quote }}
          adminUserSecret: {{- .Values.components.keycloak.adminSecret | toYaml | nindent 12 }}
        {{- end }}

        database:
          dbname: {{ .Values.database.dbname | quote }}
          port: {{ .Values.database.port }}
          hostname: {{ include "databaseHostname" . | quote }}
          userSecret: {{ include "databaseSuperUserSecretName" . | quote }}

        publicUrl: {{ include "fuegoUrl" . | quote }}

        oidc:
          enabled: {{ .Values.oidc.enabled }}
          discoveryUrl: {{ include "oidcDiscoveryUrl" . | quote }}
          clientSecret: {{ .Values.components.fuego.oidcClientSecret | toYaml | nindent 12 }}

        caCertsConfigMap:
          enabled: {{ .Values.caCertsConfigMap.enabled }}
          name: {{ include "caCertsConfigMapName" . | quote }}
          fileName: {{ .Values.caCertsConfigMap.fileName | quote }}

        hapi:
          enabled: {{ .Values.components.fuego.hapi.enabled }}
          image: {{ .Values.components.fuego.hapi.image | quote }}

          {{- with .Values.components.fuego.hapi.securityContext }}
          securityContext: {{- . | toYaml | nindent 12 }}
          {{- end }}

          {{- with .Values.components.fuego.hapi.env }}
          env: {{ . | toYaml | nindent 12 }}
          {{- end }}

          {{- with .Values.components.fuego.hapi.initContainers }}
          initContainers: {{ . | toYaml | nindent 12 }}
          {{- end }}

          {{- with .Values.components.fuego.hapi.volumes }}
          volumes: {{ . | toYaml | nindent 12 }}
          {{- end }}

          {{- with .Values.components.fuego.hapi.volumeMounts }}
          volumeMounts: {{ . | toYaml | nindent 12 }}
          {{- end }}

          features: {{ .Values.components.fuego.hapi.features | toYaml | nindent 12 }}

          service:
            nameOverride: {{ include "fuegoAppName" . }}-hapi

          oidc:
            enabled: {{ .Values.oidc.enabled }}
            discoveryUrl: {{ include "oidcDiscoveryUrl" . | quote }}
            clientSecret: {{ .Values.components.fuego.hapi.oidcClientSecret | toYaml | nindent 14 }}
      {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}

  {{- with .Values.syncPolicy }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end -}}
{{- end -}}
