{{- if .Values.components.postgres.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "postgresAppName" . }}
  namespace: {{ .Values.argoCdNamespace | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.chartRepoUrl | quote }}
    {{ include "chartSelection" (dict "context" . "chart" "fmx-postgres") }}
    targetRevision: {{ include "chartRevision" . | quote }}
    helm:
      releaseName: {{ include "postgresAppName" . }}
      values: |
      {{- if .Values.components.postgres.valuesOverride }}
        {{- .Values.components.postgres.valuesOverride | toYaml | nindent 8 }}
      {{- else }}
        image: {{ include "spiloImage" . | quote }}
        imagePullSecret: {{ .Values.imagePullSecret | quote }}
        podServiceAccountNameOverride: {{ .Values.components.postgres.podServiceAccountNameOverride | quote }}
        numberOfInstances: {{ .Values.components.postgres.numberOfInstances }}

        enableMasterLoadBalancer: {{ .Values.components.postgres.enableMasterLoadBalancer }}
        enableReplicaLoadBalancer: {{ .Values.components.postgres.enableReplicaLoadBalancer }}
        {{- with .Values.components.postgres.allowedSourceRanges }}
        allowedSourceRanges: {{- . | toYaml | nindent 10 }}
        {{- else }}
        allowedSourceRanges: []
        {{- end }}

        teamId: {{ .Values.components.postgres.teamId | quote }}
        spiloRunAsUser: {{ .Values.components.postgres.spiloRunAsUser }}
        spiloRunAsGroup: {{ .Values.components.postgres.spiloRunAsGroup }}
        spiloFSGroup: {{ .Values.components.postgres.spiloFSGroup }}

        {{- with .Values.components.postgres.volume }}
        volume: {{- . | toYaml | nindent 10 }}
        {{- end }}

        {{- with .Values.components.postgres.resources }}
        resources: {{- . | toYaml | nindent 10 }}
        {{- end }}

        postgresql:
          version: {{ .Values.components.postgres.postgresql.version | quote }}
          {{- with (dict "fmx.database_name" .Values.database.dbname "fmx.worker_count" (toString .Values.workerCount) "fmx.base_url" (include "fhirBaseUrl" .) "fmx.enforce_referential_integrity_on_write" (toString .Values.referentialIntegrity.enforceOnWrite) "fmx.enforce_referential_integrity_on_delete" (toString .Values.referentialIntegrity.enforceOnDelete)) | merge (deepCopy .Values.components.postgres.postgresql.parameters) }}
          parameters: {{- . | toYaml | nindent 12 }}
          {{- end }}

        {{- if .Values.backup.enabled }}
        backup: {{- .Values.backup | toYaml | nindent 10 }}
        {{- end }}

        {{- with .Values.components.postgres.extraEnv }}
        env: {{- . | toYaml | nindent 10 }}
        {{- end }}

      {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}

  {{- with .Values.syncPolicy }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end -}}
{{- end -}}
