publicUrl: "http://example.com/fhir"
image: ghcr.io/firemetrics/fuego:v0.8.1
serviceAccountName: ""
imagePullSecret: ""
initContainers: []
env: []
logging:
  # -- The log format for Fuego ("plain" or "json").
  format: json
volumes: []
volumeMounts: []

bootstrapKeycloak:
  enabled: false
  image: curlimages/curl:8.15.0
  url: "https://example.com/auth"
  realm: "firemetrics"
  adminUserSecret:
    name: keycloak-admin
    usernameKey: username
    passwordKey: password

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe: {}

readinessProbe: {}

database:
  hostname: postgres
  dbname: firemetrics
  port: 5432
  userSecret: fuego-user

service:
  enabled: true
  nameOverride: ""

oidc:
  enabled: false
  discoveryUrl: ""
  clientSecret:
    name: "fuego-oidc-client"
    idKey: "id"
    secretKey: "secret"

caCertsConfigMap:
  enabled: false
  name: "ca-certs"
  fileName: "ca-certificates.crt"

hapi:
  enabled: true
  image: ghcr.io/firemetrics/fmx-hapi-facade:0.1.6
  serviceAccountName: ""
  initContainers: []
  env: []
  volumes: []
  volumeMounts: []

  features:
    validation:
      enabled: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  service:
    enabled: true
    nameOverride: ""

  oidc:
    enabled: false
    discoveryUrl: ""
    clientSecret:
      name: "hapi-oidc-client"
      idKey: "id"
      secretKey: "secret"
