{{- if .Values.alloy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alloyClusterRoleName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alloyClusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "alloyServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
