publicUrl: http://example.com/auth
publicPath: /auth
image: quay.io/keycloak/keycloak:26.3.2
imagePullSecret: ""
initContainers: []
env: []
volumes: []
volumeMounts: []
securityContext: {}

database:
  hostname: postgres
  port: 5432
  dbname: keycloak
  userSecret:
    name: keycloak-db-user
    usernameKey: username
    passwordKey: password

bootstrap:
  enabled: true
  image: ghcr.io/zalando/spilo-17:4.0-p2
  databaseUserSecret:
    name: keycloak-bootstrap-db-user
    usernameKey: username
    passwordKey: password

adminSecret:
  name: "keycloak-admin"
  usernameKey: username
  passwordKey: password

service:
  enabled: true
  nameOverride: ""

importRealm:
  enabled: true
  realmName: firemetrics

caCertsConfigMap:
  enabled: false
  name: "ca-certs"
  fileName: "ca-certificates.crt"

panel:
  oidcAudience: "panel"

fuego:
  oidcAudience: "fuego"
