{{- if and .Values.loki.enabled .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lokiSvcName" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/part-of: {{ include "appName" . }}
    app.kubernetes.io/component: loki
    app.kubernetes.io/name: {{ include "lokiPodLabel" . }}
{{- end -}}
